import type { StaticImageData } from 'next/image'

import kitfo2 from '@/assets/images/kitfo-2.jpg'
import kitfo3 from '@/assets/images/kitfo-3.jpg'
import kitfo4 from '@/assets/images/kitfo-4.jpg'
import kitfoPro from '@/assets/images/kitfo-pro.jpg'
import kitfoPro2 from '@/assets/images/kitfo-pro-2.jpg'
import kitfoServe from '@/assets/images/kitfo-serve.jpg'
import view1 from '@/assets/images/view-1.jpg'
import view2 from '@/assets/images/view-2.jpg'
import view3 from '@/assets/images/view-3.jpg'
import view4 from '@/assets/images/view-4.jpg'
import view5 from '@/assets/images/view-5.jpg'
import logo from '@/assets/images/logo/logo-1.jpg'

// Attention-cropped squares, generated by scripts/optimize-images.ts. Used
// anywhere a photo is shown in a square or near-square frame, so the studio
// shots on white sweeps do not render as mostly-empty cards.
import sqKitfo2 from '@/assets/images/square/kitfo-2.jpg'
import sqKitfo3 from '@/assets/images/square/kitfo-3.jpg'
import sqKitfo4 from '@/assets/images/square/kitfo-4.jpg'
import sqKitfoPro from '@/assets/images/square/kitfo-pro.jpg'
import sqKitfoPro2 from '@/assets/images/square/kitfo-pro-2.jpg'
import sqKitfoServe from '@/assets/images/square/kitfo-serve.jpg'
import sqView1 from '@/assets/images/square/view-1.jpg'
import sqView2 from '@/assets/images/square/view-2.jpg'
import sqView3 from '@/assets/images/square/view-3.jpg'
import sqView4 from '@/assets/images/square/view-4.jpg'
import sqView5 from '@/assets/images/square/view-5.jpg'

/**
 * Bundled photography. Imported statically so next/image gets intrinsic
 * dimensions and an automatic blurDataURL placeholder — the blur is what
 * makes a 700 KB hero feel instant on a slow Addis connection.
 */
export const photos = {
  'kitfo-2': kitfo2,
  'kitfo-3': kitfo3,
  'kitfo-4': kitfo4,
  'kitfo-pro': kitfoPro,
  'kitfo-pro-2': kitfoPro2,
  'kitfo-serve': kitfoServe,
  'view-1': view1,
  'view-2': view2,
  'view-3': view3,
  'view-4': view4,
  'view-5': view5,
} satisfies Record<string, StaticImageData>

export const squarePhotos = {
  'kitfo-2': sqKitfo2,
  'kitfo-3': sqKitfo3,
  'kitfo-4': sqKitfo4,
  'kitfo-pro': sqKitfoPro,
  'kitfo-pro-2': sqKitfoPro2,
  'kitfo-serve': sqKitfoServe,
  'view-1': sqView1,
  'view-2': sqView2,
  'view-3': sqView3,
  'view-4': sqView4,
  'view-5': sqView5,
} satisfies Record<string, StaticImageData>

export type PhotoKey = keyof typeof photos

export const logoMark = logo

/** Named roles, so pages reference intent rather than a filename. */
export const heroPhoto = photos['kitfo-4']
export const storyPhoto = photos['kitfo-serve']
export const cateringPhoto = photos['kitfo-2']
export const eventsPhoto = photos['view-4']
export const terracePhoto = photos['view-1']
export const barPhoto = photos['view-2']
export const diningPhoto = photos['view-3']

/**
 * Dish photography. Only dishes we genuinely have a photograph of are mapped;
 * the rest render a typographic card instead. Showing a picture of kitfo next
 * to "Fasting Beyaynetu" would be a lie, and a menu that lies about the food
 * is worse than one with no pictures.
 */
export const dishPhotos: Partial<Record<string, StaticImageData>> = {
  'tamem-special-kitfo': sqKitfoPro,
  'gurage-kitfo-clay': sqKitfoPro2,
  'tamem-special-dulet': sqKitfo3,
  'royal-agelgil': sqKitfo2,
  'honey-tej': sqView2,
}

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? ''

/**
 * Resolves a stored image reference to something next/image can render.
 *
 * - "local:view-1"      -> the bundled StaticImageData (used by fixtures)
 * - "gallery/abc.jpg"   -> a public Supabase Storage URL (used by the CMS)
 * - full URL            -> passed through
 */
export function resolveImage(
  path: string | null | undefined,
  bucket: 'gallery' | 'dishes' = 'gallery',
): StaticImageData | string | null {
  if (!path) return null
  if (path.startsWith('local:')) {
    const key = path.slice('local:'.length)
    return (photos as Record<string, StaticImageData>)[key] ?? null
  }
  if (path.startsWith('http://') || path.startsWith('https://')) return path
  if (!SUPABASE_URL) return null
  return `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${path}`
}

/**
 * Square-framed variant of a stored reference. Falls back to the full image
 * for anything uploaded through the CMS, which has no square derivative.
 */
export function resolveSquareImage(
  path: string | null | undefined,
): StaticImageData | string | null {
  if (path?.startsWith('local:')) {
    const key = path.slice('local:'.length)
    const square = (squarePhotos as Record<string, StaticImageData>)[key]
    if (square) return square
  }
  return resolveImage(path)
}

/** Dish image with graceful degradation: uploaded photo, then bundled, then none. */
export function resolveDishImage(
  slug: string,
  imagePath: string | null | undefined,
): StaticImageData | string | null {
  return resolveImage(imagePath, 'dishes') ?? dishPhotos[slug] ?? null
}
